package edu.gwu.tennistalk

data class Match(
    val tournament: String,
    val country: String,
    val city: String,
    val tour: String,
    val surface: String,
    val startDate: String,
    val endDate: String,

    val title: String,
    val status: String,
    val home_player: String,
    val home_id: Int,
    val away_player: String,
    val away_id: Int,
    val date: String,
    val round_id: Int,
    val round_name: String,
    val id: Int,
    val winner_id: Int,
    val home_sets: String,
    val away_sets: String,
    val home_set1: String,
    val home_set2: String,
    val home_set3: String,
    val home_set4: String,
    val home_set5: String,
    val away_set1: String,
    val away_set2: String,
    val away_set3: String,
    val away_set4: String,
    val away_set5: String,
)
